"use strict";
let places = ["Turkey", "Saudi Arabia", "Iraq", "Italy", "Germany"];
console.log('Orignal ' + places);
console.log('Copy ' + [...places].sort());
console.log('Orignal ' + places);
console.log('Copy ' + [...places].sort().reverse());
console.log('Orignal ' + places);
console.log('Orignal ' + places.reverse());
console.log('Orignal ' + places.reverse());
console.log('Orignal ' + places.sort());
console.log('Orignal ' + places.sort().reverse());
